Public List, Users and Role Detection, Record Statuses
CenterForDigitalHumanities/dunbar-poems pull request #20
Opened 2023-03-03 19:19 UTC by thehabes

2023-03-03 20:22 UTC, thehabes commented
Tested and seems functional, using the same status templates as from deer-letters.

2023-03-06 16:07 UTC, cubap requested changes
small things, but worth changing

2023-03-06 18:41 UTC, thehabes commented on js/deer-config.js
> +                                    elem.querySelector(".textSample").innerHTML = poemText.innerHTML
I did not change anything here as this was required to get the page to load.  Let me know if we have to change something now or if we can just ticket this.

2023-03-06 18:42 UTC, thehabes commented on js/deer-config.js
>          managedlist: (obj, options = {}) => {
Separate issue (and we need to do the same in Dunbar Letters, I will make an issue.)

2023-03-06 18:42 UTC, thehabes commented on js/deer-config.js
> +            if(!userHasRole(["dunbar_user_admin","dunbar_user_contributor","dunbar_user_public"])) { return `This function is limited to contributors.`}
separate issue

2023-03-06 18:43 UTC, thehabes commented on js/deer-render.js
> +                        return
Changed, I think the goal was to remove the `click` listener.

2023-03-06 18:44 UTC, thehabes commented on js/deer-render.js
> +                    return false
else is removed, but the result should be boolean so false is still returned

2023-03-06 18:44 UTC, thehabes commented on js/deer-render.js
> +                    rejected = (!data[0].body.releasedTo && data[0].body.resultComment) ? true : false
see slack comments.  Does not need ternary, but result should be boolean.

2023-03-06 18:44 UTC, thehabes commented on js/deer-render.js
> +                    if(data[0].body.releasedTo ? true : false){
cleaned up.

2023-03-06 18:45 UTC, thehabes commented on js/deer-render.js
> +                    //reviewed = accepted || rejected
cleaned up

2023-04-06 16:37 UTC, merged